import 'angular';
import 'angular-jwt';
import 'ngstorage';
import 'angular-dynamic-locale';
import 'angular-translate';
import 'angular-resource';
import 'angular-cookies';
import 'angular-aria';
import 'angular-cache-buster';
import 'ng-file-upload';
import 'angular-ui-bootstrap';
import 'ui-select';
import 'bootstrap-ui-datetime-picker';
import 'bootstrap';
import 'bootstrap-toggle'
import 'oclazyload';
import '@uirouter/angularjs'
import '@uirouter/angularjs/release/stateEvents'
import 'ng-infinite-scroll';
import 'angular-minicolors';
import 'angular-split-pane';
import 'gridstack-angular';
import 'ng-tags-input';
import 'angular-sanitize';
import 'angular-pageslide-directive';
import 'angular-ui-tree';
import 'angular-wizard';
import 'angular-material';
import 'tinycolor2';
import 'md-color-picker';
import 'angular-filter';
import 'angular-drag-and-drop-lists';
import 'angularjs-slider';
import 'angular-cron-gen';
import 'angular-translate-interpolation-messageformat';
import 'angular-translate-loader-partial';
import 'jquery';
import 'popper.js';

import 'content/js/custom';
import 'content/js/icheck';
import 'content/js/sweetalert.min';
